#!/bin/bash

. install-nala
install_nala
echo "************ Install packages..."
sudo nala install -y zsh neovim curl wget neofetch tree bat exa
echo "************ Configure neovim..."
DIR="$HOME/.config"
if [ -d "$DIR" ]; then
  echo "$HOME/.config EXITS"
else
  mkdir ~/.config
fi
cd ~/.config
git clone https://github.com/CGary/nvim.git
cd nvim
wget -P autoload https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cd
cp .bash_aliases ~/
echo "if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi" >> .zshrc
echo "************ Install ohmyzsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#END
