#!/bin/bash

cp .bash_aliases ~/
echo "************ Install packages..."
sudo nala install -y zsh curl wget neofetch tree bat exa
echo "************ Configure neovim..."

if [ -d "$HOME/.Downloads" ]; then
	echo "$HOME/.Downloads EXITS"
else
	mkdir "$HOME/.Downloads"
fi
cd ~/.Downloads
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux64.tar.gz
rm nvim-linux64.tar.gz
cd

if [ -d "$HOME/.config" ]; then
	echo "$HOME/.config EXITS"
else
	mkdir "$HOME/.config"
fi

git clone https://github.com/CGary/nvim.git ~/.config/nvim

echo "************ Install ohmyzsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#END
