#!/bin/bash

. install-nala
install_nala
echo "************ Install packages..."
sudo nala install -y terminator pip
pip install requests
mkdir -p $HOME/.config/terminator/plugins
wget https://git.io/v5Zww -O $HOME"/.config/terminator/plugins/terminator-themes.py"

#END
