#!/bin/bash

echo "************ Install packages..."
sudo nala install -y software-properties-common firmware-realtek firmware-linux-free firmware-linux-nonfree firmware-misc-nonfree make gcc build-essential dkms linux-headers-$(uname -r) gnupg gnupg2 apt-transport-https lsb-release

echo '# neovim\nexport PATH="$PATH:/opt/nvim-linux64/bin"' >>~/.zshrc

#END
