#!/bin/bash

. install-nala
install_nala

curl -sSL https://gist.githubusercontent.com/CGary/e6c547f39dab6e150afe1b4b5bbea96b/raw/20503e6f79253d13e0d58215ded2507f0b90015c/install_docker.sh | sh

#END
